routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/admin', function () {
//    return view('backend.dashboard');
//});



//for Frontend Section
Route::get('/', 'HomeController@index')->name('frontend.home');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::get('/posts', 'PostController@allPost')->name('post.allpost');
Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('/subscriber', 'SubscriberController@store')->name('subscriber.store');

//Authorization Section
Auth::routes();

//Post Favroutie Section
Route::group(['middleware'=>['auth']], function (){
    Route::post('favourite/{post}/add', 'FavouriteController@add')->name('favourite.post');
    Route::post('comment/{post}' ,'CommentController@store')->name('comment.store');
});


//prefix acts like ( admin.dashboard in the url) & namespace acts folder path &&&& [as] use here like admin.index for route name section

Route::group([ 'as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin' , 'middleware'=>['auth','admin']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/tag', 'TagController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');

    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber' ,'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}' ,'SubscriberController@destroy')->name('subscriber.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');

    Route::put('/post/{id}/approve', 'PostController@approve')->name('post.approve');
    Route::get('/pending/post','PostController@pending')->name('post.pending');


});

Route::group([ 'as'=>'author.', 'prefix'=>'author', 'namespace'=>'Author' , 'middleware'=>['auth','author']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');
    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');
});

resources/views/layouts/backend/backendDesign.blade.php
<!DOCTYPE HTML>
<html lang="en">
<head>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')-{{ config('app.name', 'Laravel') }}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">


    <!-- Favicon-->
    <link rel="icon" href="{{asset('assets/backend/favicon.ico')}}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('assets/backend/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('assets/backend/plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('assets/backend/plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Morris Chart Css-->
    <link href="{{ asset('assets/backend/plugins/morrisjs/morris.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('assets/backend/css/style.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset('assets/backend/css/themes/all-themes.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    @stack('css')


</head>
<body class="theme-light-blue">

<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
@include('layouts.backend.backendHeader')
@include('layouts.backend.backendSidebar')

@yield('content')


<!-- Jquery Core Js -->
<script src="{{ asset('assets/backend/plugins/jquery/jquery.min.js') }}"></script>

<!-- Bootstrap Core Js -->
<script src="{{ asset('assets/backend/plugins/bootstrap/js/bootstrap.js') }}"></script>

<!-- Select Plugin Js -->
{{--<script src="{{ asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>--}}

<!-- Slimscroll Plugin Js -->
<script src="{{ asset('assets/backend/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

<!-- Waves Effect Plugin Js -->
<script src="{{ asset('assets/backend/plugins/node-waves/waves.js') }}"></script>



<!-- Custom Js -->
<script src="{{ asset('assets/backend/js/admin.js') }}"></script>


<!-- Demo Js -->
<script src="{{ asset('assets/backend/js/demo.js') }}"></script>
<script src=" https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
{!! Toastr::message() !!}
<script>
    @if($errors->any())
        @foreach($errors->all() as $error)
        toastr.error('{{ $error }}','Error',{
            closeButton:true,
            progressBar:true,
        });
        @endforeach
    @endif
</script>
@stack('js')
</body>
</html>

resources/views/layouts/backend/backendHeader.blade.php
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
               data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand"
                @if(Auth::user()->role->id == 1)
                    href="{{route('admin.dashboard')}}"
                @else
                    href="{{route('author.dashboard')}}"
                @endif
            >Backend-Portal</a>
        </div>
        {{--        <div class="collapse navbar-collapse" id="navbar-collapse">--}}
        {{--            <ul class="nav navbar-nav navbar-right">--}}
        {{--                <!-- Notifications -->--}}
        {{--                <li class="dropdown">--}}
        {{--                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">--}}
        {{--                        <i class="material-icons">notifications</i>--}}
        {{--                        <span class="label-count">7</span>--}}
        {{--                    </a>--}}
        {{--                    <ul class="dropdown-menu">--}}
        {{--                        <li class="header">NOTIFICATIONS</li>--}}
        {{--                        <li class="body">--}}
        {{--                            <ul class="menu">--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-light-green">--}}
        {{--                                            <i class="material-icons">person_add</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4>12 new members joined</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 14 mins ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-cyan">--}}
        {{--                                            <i class="material-icons">add_shopping_cart</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4>4 sales made</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 22 mins ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-red">--}}
        {{--                                            <i class="material-icons">delete_forever</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4><b>Nancy Doe</b> deleted account</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 3 hours ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-orange">--}}
        {{--                                            <i class="material-icons">mode_edit</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4><b>Nancy</b> changed name</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 2 hours ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-blue-grey">--}}
        {{--                                            <i class="material-icons">comment</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4><b>John</b> commented your post</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 4 hours ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-light-green">--}}
        {{--                                            <i class="material-icons">cached</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4><b>John</b> updated status</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> 3 hours ago--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                                <li>--}}
        {{--                                    <a href="javascript:void(0);">--}}
        {{--                                        <div class="icon-circle bg-purple">--}}
        {{--                                            <i class="material-icons">settings</i>--}}
        {{--                                        </div>--}}
        {{--                                        <div class="menu-info">--}}
        {{--                                            <h4>Settings updated</h4>--}}
        {{--                                            <p>--}}
        {{--                                                <i class="material-icons">access_time</i> Yesterday--}}
        {{--                                            </p>--}}
        {{--                                        </div>--}}
        {{--                                    </a>--}}
        {{--                                </li>--}}
        {{--                            </ul>--}}
        {{--                        </li>--}}
        {{--                        <li class="footer">--}}
        {{--                            <a href="javascript:void(0);">View All Notifications</a>--}}
        {{--                        </li>--}}
        {{--                    </ul>--}}
        {{--                </li>--}}
        {{--                <!-- #END# Notifications -->--}}
        {{--            </ul>--}}
        {{--        </div>--}}
    </div>
</nav>
<!-- #Top Bar -->

resources/views/layouts/backend/backendSidebar.blade.php
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="{{asset('assets/backend/images/user.png')}}" width="48" height="48" alt="User" />
            </div>
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{\Illuminate\Support\Facades\Auth::user()->username}}</div>
                <div class="email">{{Auth::user()->email}}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="javascript:void(0);"><i class="material-icons">person</i>Profile</a></li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i class="material-icons">input</i>Sign Out
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
{{--                            <a href="javascript:void(0);"><i class="material-icons">input</i>Sign Out</a>--}}

                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MAIN NAVIGATION</li>
                @if(Request::is('admin*'))
                    <li class="{{Request::is('admin/dashboard') ? 'active' : '' }}">
                        <a href="{{route('admin.dashboard')}}">
                            <i class="material-icons">dashboard</i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/tag*') ? 'active' : '' }}">
                        <a href="{{ route('admin.tag.index') }}">
                            <i class="material-icons">label</i>
                            <span>Tag</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/category*') ? 'active' : '' }}">
                        <a href="{{ route('admin.category.index') }}">
                            <i class="material-icons">apps</i>
                            <span>Category</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/post*') ? 'active' : '' }}">
                        <a href="{{ route('admin.post.index') }}">
                            <i class="material-icons">library_books</i>
                            <span>Post</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/pending') ? 'active' : '' }}">
                        <a href="{{ route('admin.post.pending') }}">
                            <i class="material-icons">library_books</i>
                            <span>Pending Post</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/favourite') ? 'active' : '' }}">
                        <a href="{{ route('admin.favourite.index') }}">
                            <i class="material-icons">favorite</i>
                            <span>Favourite Post</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/comment') ? 'active' : '' }}">
                        <a href="{{ route('admin.comment.index') }}">
                            <i class="material-icons">comment</i>
                            <span>Comments</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('admin/pending') ? 'active' : '' }}">
                        <a href="{{ route('admin.subscriber.index') }}">
                            <i class="material-icons">subscriptions</i>
                            <span>Subscriber</span>
                        </a>
                    </li>
                    <li class="header">System</li>
                    <li class="{{ Request::is('admin/settings') ? 'active' : '' }}">
                        <a href="{{ route('admin.settings') }}">
                            <i class="material-icons">settings</i>
                            <span>Settings</span>
                        </a>
                    </li>
                    <li class="">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">logout</i>
                            <span>Logout</span>
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endif

                @if(Request::is('author*'))
                    <li class="{{Request::is('author/dashboard') ? 'active' : '' }}">
                        <a href="{{route('author.dashboard')}}">
                            <i class="material-icons">dashboard</i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('author/post*') ? 'active' : '' }}">
                        <a href="{{ route('author.post.index') }}">
                            <i class="material-icons">library_books</i>
                            <span>Post</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('author/favourite') ? 'active' : '' }}">
                        <a href="{{ route('author.favourite.index') }}">
                            <i class="material-icons">favorite</i>
                            <span>Favourite Post</span>
                        </a>
                    </li>
                    <li class="{{ Request::is('author/comment') ? 'active' : '' }}">
                        <a href="{{ route('author.comment.index') }}">
                            <i class="material-icons">comment</i>
                            <span>Comments</span>
                        </a>
                    </li>
                    <li class="header">System</li>
                    <li class="{{ Request::is('author/settings') ? 'active' : '' }}">
                        <a href="{{ route('author.settings') }}">
                            <i class="material-icons">settings</i>
                            <span>Settings</span>
                        </a>
                    </li>
                    <li class="">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">logout</i>
                            <span>Logout</span>
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endif

            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2020 <a href="javascript:void(0);">Amit Saha</a>.
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
</section>