routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/admin', function () {
//    return view('backend.dashboard');
//});



//for Frontend Section
Route::get('/', 'HomeController@index')->name('frontend.home');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::get('/posts', 'PostController@allPost')->name('post.allpost');
Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('/subscriber', 'SubscriberController@store')->name('subscriber.store');

//Authorization Section
Auth::routes();

//Post Favroutie Section
Route::group(['middleware'=>['auth']], function (){
    Route::post('favourite/{post}/add', 'FavouriteController@add')->name('favourite.post');
    Route::post('comment/{post}' ,'CommentController@store')->name('comment.store');
});


//prefix acts like ( admin.dashboard in the url) & namespace acts folder path &&&& [as] use here like admin.index for route name section

Route::group([ 'as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin' , 'middleware'=>['auth','admin']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/tag', 'TagController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');

    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber' ,'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}' ,'SubscriberController@destroy')->name('subscriber.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');

    Route::put('/post/{id}/approve', 'PostController@approve')->name('post.approve');
    Route::get('/pending/post','PostController@pending')->name('post.pending');


});

Route::group([ 'as'=>'author.', 'prefix'=>'author', 'namespace'=>'Author' , 'middleware'=>['auth','author']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');
    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public function user(){
        return $this->belongsTo('App\User');
    }
    public function post(){
        return $this->belongsTo('App\Post');
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comment;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class CommentController extends Controller
{
   public function index(){
       $comments = Comment::latest()->get();
       return view('backend.comment.index',compact('comments'));
   }
   public function destroy(Comment $comment){
       $comment->delete();
       Toastr::success('Comment Successfully Deleted :)', 'Success');
       return redirect()->back();
   }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index(){
        $posts = Auth::user()->posts()->latest()->get();
        return view('author.comment.index',compact('posts'));
    }
    public function destroy($id){
        $comment = Comment::findOrFail($id);
        if ($comment->post->user->id == Auth::id())
        {
            $comment->delete();
            Toastr::success('Comment Successfully Deleted','Success');
        } else {
            Toastr::error('You are not authorized to delete this comment :(','Access Denied !!!');
        }
        return redirect()->back();
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function store(Request $request , $post){
        $this->validate($request,[
            'comment' => 'required'
            ]);
        $comment = new Comment();
        $comment->post_id = $post;
        $comment->user_id = Auth::id();
        $comment->comment = $request->comment;
        $comment->save();
        Toastr::success('Comment successfully posted','Success');
        return redirect()->back();
    }
}

resources/views/backend/comment/index.blade.php
@extends('layouts.backend.backendDesign')
@section('title' , 'Comments')
@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush
@section('content')
    <section class="content">
        <div class="container-fluid">
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                All Comments  List
                                <span class="badge bg-blue">{{$comments->count()}}</span>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                    <tr>
                                        <th class="text-center">Comment Info</th>
                                        <th class="text-center">Post Info</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($comments as $key=>$comment)
                                        <tr>
                                            <td>
                                                <div class="media">
                                                    <div class="media-left">
                                                        <a href="#">
                                                            <img class="media-object"
                                                                 src="{{asset('storage/profile/'.$comment->user->image)}}"
                                                                 height="64" width="64" alt="">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <h4 class="media-heading">
                                                            {{$comment->user->name}} <small>
                                                                {{$comment->created_at->diffForHumans()}}
                                                            </small>
                                                        </h4>
                                                        <p>{{$comment->comment}}</p>
                                                        <a target="_blank" href="{{route('post.details',$comment->post->slug.'#comments')}}">Reply</a>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="media">
                                                    <div class="media-right">
                                                        <a target="_blank" href="{{route('post.details',$comment->post->slug)}}">
                                                            <img class="media-object"
                                                                 src="{{asset('storage/'.$comment->post->image)}}"
                                                                 height="64" width="64" alt="">
                                                        </a>
                                                    </div>
                                                    <div class="media-body">
                                                        <a target="_blank" href="{{route('post.details',$comment->post->slug)}}">
                                                            <h4 class="media-heading">
                                                                {{Str::limit($comment->post->title,'40')}}
                                                            </h4>
                                                        </a>
                                                        <p>
                                                            by <strong>{{$comment->post->user->name}}</strong>
                                                        </p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <button class="btn btn-danger waves-effect" type="button" onclick="deletePost({{ $comment->id }})">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="delete-form-{{ $comment->id }}" action="{{ route('admin.comment.destroy',$comment->id) }}" method="POST">
                                                    {{csrf_field()}}
                                                    {{method_field('DELETE')}}
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
    </section>
    @push('js')
        <!-- Jquery DataTable Plugin Js -->
        <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
        <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
        <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
        <script src=" https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
        <script type="text/javascript">
            function deletePost(id) {
                swal({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'No, cancel!',
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger',
                    buttonsStyling: false,
                    reverseButtons: true
                }).then((result) => {
                    if (result.value) {
                        event.preventDefault();
                        document.getElementById('delete-form-'+id).submit();
                    } else if (
                        // Read more about handling dismissals
                        result.dismiss === swal.DismissReason.cancel
                    ) {
                        swal(
                            'Cancelled',
                            'Your data is safe :)',
                            'error'
                        )
                    }
                })
            }
        </script>
    @endpush

@stop