routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/admin', function () {
//    return view('backend.dashboard');
//});



//for Frontend Section
Route::get('/', 'HomeController@index')->name('frontend.home');
Route::get('post/{slug}', 'PostController@details')->name('post.details');
Route::get('/posts', 'PostController@allPost')->name('post.allpost');
Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::post('/subscriber', 'SubscriberController@store')->name('subscriber.store');

//Authorization Section
Auth::routes();

//Post Favroutie Section
Route::group(['middleware'=>['auth']], function (){
    Route::post('favourite/{post}/add', 'FavouriteController@add')->name('favourite.post');
    Route::post('comment/{post}' ,'CommentController@store')->name('comment.store');
});


//prefix acts like ( admin.dashboard in the url) & namespace acts folder path &&&& [as] use here like admin.index for route name section

Route::group([ 'as'=>'admin.', 'prefix'=>'admin', 'namespace'=>'Admin' , 'middleware'=>['auth','admin']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/tag', 'TagController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');

    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');

    Route::get('/subscriber' ,'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}' ,'SubscriberController@destroy')->name('subscriber.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');

    Route::put('/post/{id}/approve', 'PostController@approve')->name('post.approve');
    Route::get('/pending/post','PostController@pending')->name('post.pending');


});

Route::group([ 'as'=>'author.', 'prefix'=>'author', 'namespace'=>'Author' , 'middleware'=>['auth','author']] , function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/post', 'PostController');
    Route::get('/favourite' ,'FavouriteController@index')->name('favourite.index');
    Route::get('/comment' ,'CommentController@index')->name('comment.index');
    Route::delete('/comment/{comment}' ,'CommentController@destroy')->name('comment.destroy');
    Route::get('/settings' ,'SettingsController@index')->name('settings');
    Route::put('/settings/profile' ,'SettingsController@updateProfile')->name('settings.profile');
    Route::put('/settings/password' ,'SettingsController@updatePassword')->name('settings.password');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user(){
        return $this->belongsTo('App\User');
    }
    public function categories()
    {
        return $this->belongsToMany('App\Category')->withTimestamps();
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }
    public function fav_to_users(){
        return $this->belongsToMany('App\User')->withTimestamps();
    }
    public function comments(){
        return $this->hasMany('App\Comment');
    }
    public function scopeApproved($query)
    {
        return $query->where('is_approved', 1);
    }
    public function scopePublished($query)
    {
        return $query->where('status', 1);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Notifications\AuthorPostApprove;
use App\Notifications\NewPostNotify;
use App\post;
use App\Subscriber;
use App\Tag;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Intervention\Image\ImageManagerStatic as Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        return view('backend.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('backend.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'status' => 'required',
            'image' => 'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required'
        ]);
        $posts = new Post();
        $posts->user_id = Auth::id();
        $posts->title = $request->title;
        $posts->slug = Str::slug($request->title);
        //image section start
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move('storage/', $fileName);
            $posts->image = $fileName;
        } else {
            $posts->image = "default.png";
        }
        //image section end

        if (isset($request->status)) {
            $posts->status = true;
        } else {
            $posts->status = false;
        }
        $posts->body = $request->body;
        $posts->is_approved = true;
        $posts->save();
        $posts->categories()->attach($request->categories);
        $posts->tags()->attach($request->tags);
        //notify subscribers when a post create
        $subscribers = Subscriber::all();
        foreach ($subscribers as $subscriber){
            Notification::route('mail' , $subscriber->email)->notify(new NewPostNotify($posts));
        }

        Toastr::success('Post created successfully', 'Success');
        return redirect()->route('admin.post.index');

    }

    /**
     * Display the specified resource.
     *
     * @param \App\post $post
     * @return \Illuminate\Http\Response
     */
    public function show(post $post)
    {
        return view('backend.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('backend.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => 'required',
            'status' => 'required',
            'image' => 'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required'
        ]);
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = Str::slug($request->title);
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move('storage/', $fileName);
            $post->image = $fileName;
        }
        if (isset($request->status)) {
            $post->status = true;
        } else {
            $post->status = false;
        }

        $post->body = $request->body;
        $post->is_approved = true;
        $post->save();
        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);
        Toastr::success('Post Updated successfully', 'Success');
        return redirect()->route('admin.post.index');
    }

    public function pending()
    {
        $posts = Post::where('is_approved', false)->get();
        return view('backend.post.pending', compact('posts'));
    }

    public function approve($id)
    {
        $posts = Post::find($id);
        if ($posts->is_approved == false) {
            $posts->is_approved = true;
            $posts->save();
            $posts->user->notify(new AuthorPostApprove($posts));
            Toastr::success('Post is successfully approved', 'Success');
        } else {
            Toastr::info('Post is already approved', 'Success');
        }
        return redirect()->route('admin.post.pending');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();
        Toastr::success('Post Successfully Deleted :)', 'Success');
        return redirect()->back();
    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use App\Comment;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index(){
        $posts = Auth::user()->posts()->latest()->get();
        return view('author.comment.index',compact('posts'));
    }
    public function destroy($id){
        $comment = Comment::findOrFail($id);
        if ($comment->post->user->id == Auth::id())
        {
            $comment->delete();
            Toastr::success('Comment Successfully Deleted','Success');
        } else {
            Toastr::error('You are not authorized to delete this comment :(','Access Denied !!!');
        }
        return redirect()->back();
    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard');
    }





}

app/Http/Controllers/Author/FavouriteController.php
<?php

namespace App\Http\Controllers\Author;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FavouriteController extends Controller
{
    public function index(){
        $posts = Auth::user()->fav_posts;
        return view('author.favourite',compact('posts'));
    }
}

app/Http/Controllers/Author/PostController.php
<?php

namespace App\Http\Controllers\Author;

use App\Category;
use App\Http\Controllers\Controller;
use App\Notifications\AuthorNotification;
use App\Post;
use App\Tag;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Intervention\Image\ImageManagerStatic as Image;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Auth::user()->posts()->latest()->get();
        return view('author.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('author.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'status' => 'required',
            'image'=>'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required'
        ]);
        $posts = new Post();
        $posts->user_id=Auth::id();
        $posts->title = $request->title;
        $posts->slug = Str::slug($request->title);

        //image section start
        if($request->hasFile('image')){
            $file = $request->file('image');
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move('storage/', $fileName);
            $posts->image = $fileName;
        }else{
            $posts->image = "default.png";
        }
        //image section end

        if(isset($request->status))
        {
            $posts->status = true;
        }else {
            $posts->status = false;
        }
        $posts->body = $request->body;
        $posts->is_approved = false;
        $posts->save();
        $posts->categories()->attach($request->categories);
        $posts->tags()->attach($request->tags);
        //use Notification
        $users = User::where('role_id', '1')->get();
        Notification::send($users, new AuthorNotification($posts));


        Toastr::success('Post created successfully','Success');
        return redirect()->route('author.post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        if ($post->user_id != Auth::id())
        {
            Toastr::error('You are not authorized to access this post','Error');
            return redirect()->back();
        }
        return view('author.post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        if ($post->user_id != Auth::id())
        {
            Toastr::error('You are not authorized to access this post','Error');
            return redirect()->back();
        }
        $categories = Category::all();
        $tags = Tag::all();
        return view('author.post.edit', compact('post','categories','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        if ($post->user_id != Auth::id())
        {
            Toastr::error('You are not authorized to access this post','Error');
            return redirect()->back();
        }
        $request->validate([
            'title' => 'required',
            'image' => 'required',
            'categories' => 'required',
            'tags' => 'required',
            'body' => 'required'
        ]);
        $post->user_id=Auth::id();
        $post->title = $request->title;
        $post->slug = Str::slug($request->title);
        if($request->hasFile('image')){
            $file = $request->file('image');
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move('storage/', $fileName);
            $post->image = $fileName;
        }
        if(isset($request->status))
        {
            $post->status = true;
        }else {
            $post->status = false;
        }

        $post->body = $request->body;
        $post->is_approved = false;
        $post->save();
        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);
        Toastr::success('Post Updated successfully','Success');
        return redirect()->route('author.post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if ($post->user_id != Auth::id())
        {
            Toastr::error('You are not authorized to access this post','Error');
            return redirect()->back();
        }
        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();
        Toastr::success('Post Successfully Deleted :)','Success');
        return redirect()->back();
    }
}

resources/views/author/post/create.blade.php
@extends('layouts.backend.backendDesign')
@section('title' , 'Post')
@push('css')
    <!-- Bootstrap Select Css -->
    <link href="{{asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet"/>
@endpush
@section('content')
    <section class="content">
        <div class="container-fluid">

            <div class="block-header">
                <a class="btn btn-primary waves-effect" href="{{ route('author.post.index') }}">
                    <i class="material-icons">login</i>
                    <span>Post-LIST</span>
                </a>
            </div>
            <!-- Vertical Layout | With Floating Label -->
            <form action="{{route('author.post.store')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row clearfix">
                    <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">
                        <div class="card">
                            <div class="header">
                                <h2>
                                    ADD NEW Post
                                </h2>
                            </div>
                            <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" name="title" id="title" class="form-control">
                                        <label class="form-label" for="name">Post Title</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="image">Featured Image</label>
                                    <input type="file" id="image" name="image" onchange="return previewImage(event)">
                                    <img  id="output" width="100" src="" alt="">
                                </div>
                                <br>
                                <div class="form-group">
                                    <input type="checkbox" id="status" name="status" class="filled-in" value="1" />
                                    <label for="status">Publish</label>
                                </div>
                               </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-10 col-sm-10 col-xs-10">
                        <div class="card">
                            <div class="header">
                                <h2>
                                    Category & Tags
                                </h2>
                            </div>
                            <div class="body">
                                    <div class="form-group form-float">
                                        <div class="form-line {{$errors->has('categories') ? 'focused error' : ''}}">
                                            <label for="category">Select Category</label>
                                            <select name="categories[]" id="category" class=" form-control show-tick"
                                                    data-live-search="true" multiple>
                                                @foreach($categories as $category)
                                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group form-float">
                                        <div class="form-line {{$errors->has('tags') ? 'focused error' : ''}}">
                                            <label for="tag">Select Tags</label>
                                            <select name="tags[]" id="tag" class=" form-control show-tick"
                                                    data-live-search="true" multiple>
                                                @foreach($tags as $tag)
                                                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <br>
                                    <a href="{{route('author.post.index')}}"
                                       class="btn btn-danger m-t-15 waves-effect">BACK</a>
                                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">SUBMIT</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- TinyMCE -->
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="header">
                                <h2>
                                    Body
                                </h2>
                            </div>
                            <div class="body">
                            <textarea id="tinymce" name="body">

                            </textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- #END# TinyMCE -->
            </form>
                <!-- Vertical Layout | With Floating Label -->
        </div>
    </section>

@stop
@push('js')
    <script type="text/javascript">
        function previewImage(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
        }
    </script>
    <!-- Select Plugin Js -->
    <script src="{{asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <!-- TinyMCE -->
    <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>
    <script>
        $(function () {
            //TinyMCE
            tinymce.init({
                selector: "textarea#tinymce",
                theme: "modern",
                height: 300,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true
            });
            tinymce.suffix = ".min";
            tinyMCE.baseURL = '{{asset('assets/backend/plugins/tinymce')}}';
        });
    </script>

@endpush

resources/views/author/post/show.blade.php
@extends('layouts.backend.backendDesign')
@section('title' , 'Post')
@push('css')

@endpush
@section('content')
    <section class="content">
        <div class="container-fluid">
            <!-- Vertical Layout | With Floating Label -->
            <a href="{{ route('author.post.index') }}" class="btn btn-danger waves-effect">BACK</a>
            @if($post->is_approved == false)
                <button type="button" class="btn btn-success waves-effect pull-right" onclick="approvePost({{ $post->id }})">
                    <i class="material-icons">done</i>
                    <span>Approve</span>
                </button>
                <form method="post" action="{{ route('author.post.approve',$post->id) }}" id="approval-form" style="display: none">
                    @csrf
                    @method('PUT')
                </form>
            @else
                <button type="button" class="btn btn-success pull-right" disabled>
                    <i class="material-icons">done</i>
                    <span>Approved</span>
                </button>
            @endif
            <br>
            <br>
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{ $post->title }}
                                <small>Posted By <strong> <a href="">{{ $post->user->name }}</a></strong> on {{ $post->created_at->toFormattedDateString() }}</small>
                            </h2>
                        </div>
                        <div class="body">
                            {!! $post->body !!}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-cyan">
                            <h2>
                                Categoryies
                            </h2>
                        </div>
                        <div class="body">
                            @foreach($post->categories as $category)
                                <span class="label bg-cyan">{{ $category->name }}</span>
                            @endforeach
                        </div>
                    </div>
                    <div class="card">
                        <div class="header bg-green">
                            <h2>
                                Tags
                            </h2>
                        </div>
                        <div class="body">
                            @foreach($post->tags as $tag)
                                <span class="label bg-green">{{ $tag->name }}</span>
                            @endforeach
                        </div>
                    </div>
                    <div class="card">
                        <div class="header bg-amber">
                            <h2>
                                Featured Image
                            </h2>
                        </div>
                        <div class="body">
                            <img class="img-responsive thumbnail" src="{{asset('/storage/' . $post->image)}}" alt="">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

@endsection

@push('js')
    <!-- Select Plugin Js -->
    <script src="{{ asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
    <!-- TinyMCE -->
    <script src="{{ asset('assets/backend/plugins/tinymce/tinymce.js') }}"></script>
    <script src="https://unpkg.com/sweetalert2@7.19.1/dist/sweetalert2.all.js"></script>
    <script>
        $(function () {
            //TinyMCE
            tinymce.init({
                selector: "textarea#tinymce",
                theme: "modern",
                height: 300,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true
            });
            tinymce.suffix = ".min";
            tinyMCE.baseURL = '{{ asset('assets/backend/plugins/tinymce') }}';
        });
        function approvePost(id) {
            swal({
                title: 'Are you sure?',
                text: "You went to approve this post ",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, approve it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('approval-form').submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'The post remain pending :)',
                        'info'
                    )
                }
            })
        }
    </script>

@endpush